KristofferC/NearestNeighbors.jl

src/utilities.jl

Very minor fix to a very confusing comment :-)  `xs[1]` is the maximum element, so this is a max heap, right?  Same comment occurs in KDTrees.jl which is where I noted and got confused about it first.

Fix max-heap comment

---

src/utilities.jl

`@inline` for select_spec! gives a ~15% speed bump for tree building and the others can't hurt...

add `@inline` to a few utility functions

---

test/test_inrange.jl
test/test_knn.jl
test/test_monkey.jl

Should fix build errors with latest BaseTestNext. See https://github.com/JuliaLang/julia/pull/14148

Replace deprecated testloop with testset macro

---

src/evaluation.jl
test/runtests.jl

Fixes #18. To resolve some method ambiguity warnings I had to define ```evaluate``` for each type in UnionMetrics, which is a bit janky - it might be preferable/safer to replace ```Distances.UnionMetrics.types``` on [this line](https://github.com/schmrlng/NearestNeighbors.jl-1/blob/370d6cc1462e93398a862c830a1466467b5a6849/src/evaluation.jl#L9) with an explicit list of the types involved, but that would create the possibility of a de-sync with Distances.jl. I've run into similar issues before with type complements/intersections in two different arguments (the other culprit here is ```Bool <: Number``` for ```do_end``` and ```break_at```) and haven't come up with a better solution than janky enumeration - if you know of a better way I can implement that instead.
For the fallback method I …

Fallback slice-based methods for column-selecting evaluate(::Metric, …)

---

src/hyperspheres.jl
test/runtests.jl
test/test_monkey.jl

The ```create_bsphere``` method [here](https://github.com/KristofferC/NearestNeighbors.jl/blob/master/src/hyperspheres.jl#L45) relies on the assumption that the metric is determined by a norm (that is, the metric is homogeneous and translation-invariant). This PR should let ```BallTree``` work with any metric.

Fix create_bsphere for metrics that are not translation-invariant or homogeneous

---

src/tree_data.jl

Before:
```
julia> KDTree(randn(3,0))
ERROR: InexactError()
in trunc at ./float.jl:379
in call at /home/josh/.julia/v0.4/NearestNeighbors/src/tree_data.jl:17
in KDTree at /home/josh/.julia/v0.4/NearestNeighbors/src/kd_tree.jl:36
in KDTree at /home/josh/.julia/v0.4/NearestNeighbors/src/kd_tree.jl:34
```
After:
```
julia> KDTree(rand(3,0))
NearestNeighbors.KDTree{Float64,Distances.Euclidean}
Number of points: 0
Dimensions: 3
Metric: Distances.Euclidean()
Reordered: true
```

Fix to stop KDTree from crashing when given empty data.

---

README.md
src/ball_tree.jl
src/brute_tree.jl
src/kd_tree.jl
src/knn.jl
src/tree_ops.jl
src/utilities.jl
test/test_knn.jl

This is necessary for generating a path between a set of points, skipping already "visited" points.

Add optional argument to knn to skip certain points.

---

.codecov.yml
.travis.yml
README.md
REQUIRE
appveyor.yml
benchmarks/runbenchmarks.jl
src/NearestNeighbors.jl
src/ball_tree.jl
src/brute_tree.jl
src/datafreetree.jl
src/evaluation.jl
src/hyperrectangles.jl
src/hyperspheres.jl
src/inrange.jl
src/kd_tree.jl
src/knn.jl
src/tree_data.jl
src/tree_ops.jl
src/utilities.jl
test/datafreetree.jl
test/runtests.jl
test/test_datafreetree.jl
test/test_inrange.jl
test/test_knn.jl
test/test_monkey.jl

Allow for entering a vector of points where a point is an instance of an `AbstractVector`. Tests should pass except the `DataFreeTree` stuff.
Need to benchmark things to see that things doesnt slow down.
Help in testing / benchmarking appreciated.
Should fix: #24, #17, #13

Allow for AbstractVector

---

src/NearestNeighbors.jl

Can call inrange, etc with a single static vector. Previously I had to wrap a 1-element vector with my query point and unwrap the output.

Better support for supplying a single SVector

---

REQUIRE

no parametric type aliases are used here currently, only
0.17 is needed for abstract type syntax

loosen compat requirement to 0.17

---

test/REQUIRE
test/runtests.jl

No longer needed since current minimum supported julia version in REQUIRE is 0.6

remove BaseTestNext

---

.vscode/settings.json
src/ball_tree.jl
src/brute_tree.jl
src/datafreetree.jl
src/hyperrectangles.jl
src/hyperspheres.jl
src/kd_tree.jl
src/tree_data.jl
src/tree_ops.jl
src/utilities.jl
test/test_datafreetree.jl
test/test_inrange.jl
test/test_knn.jl

Since data is eventually copied as an `Array` when reordered, there is no need to restrict it to be an `Array`. By allowing it to be an `AbstractArray` we can do things like `KDTree(view(pointcloud, 10:50))`, which is a great way to find neighbors within a subset of a pointcloud. As far as I can see, there is no performance penalty from this.
NOTE: I thought about the possibility of extending the definition of `struct`s to also allow store data to be more general than `Array` without copying it (as would be needed when we do, say, `KDTree(data, reorder = false)`), but it seems this possibility (`reorder = false`) is not part of the API, so this should never be necessary.

Accept AbstractArray data (e.g. views)

---

src/NearestNeighbors.jl
src/ball_tree.jl
src/brute_tree.jl
src/evaluation.jl
src/kd_tree.jl

Once https://github.com/JuliaStats/Distances.jl/pull/150 is merged, all `UnionMetrics` will have a `parameters` trait, most of which have `nothing`, but some do have an array with weights or periods. This requires some adaptation in the `evaluation.jl` code here.

Necessary adaption of evaluation to parameter trait for UnionMetrics in Distances.jl

---

README.md
src/NearestNeighbors.jl
src/knn.jl
test/test_knn.jl

If a user wants a single nearest neighbor, unwrapping the return values is a bit cumbersome, when this can be transparently handled by the package instead.
I've added `nn` functions for this purpose, which pass the data along to `knn` with `k = 1` function and unwraps the results.
Also added tests for same.
Open to renaming them `knn` for consistency. EDIT: But I guess that would make the result type-unstable, and thus shouldn't be done.

Added convenience functions for 1 nearest neighbor

---

src/ball_tree.jl
src/brute_tree.jl
src/kd_tree.jl
test/test_inrange.jl
test/test_knn.jl

Added Tree constructors that accept a Vector, convert it to a Matrix via `reshape`, and pass it along to the Matrix-oriented constructors. Also a couple formatting nits.
Fixes suggestion #76

Added handling for single point presented as Vector

---

src/ball_tree.jl
src/brute_tree.jl
src/kd_tree.jl
src/knn.jl
src/tree_ops.jl

Removes some unwanted nonspecialization.
Benchmark:
```julia
dim = 3;
n_points = 10^6;
X = rand(dim, n_points);
k = 10;
using NearestNeighbors;
@time kd_tree = KDTree(X);
@btime knn(kd_tree, X, k);
```
PR:
```julia
julia> @btime knn(kd_tree, X, k);
2.645 s (2000008 allocations: 343.32 MiB)
```
Master
```julia
julia> @btime knn(kd_tree, X, k);
2.867 s (5000009 allocations: 511.17 MiB)
```
Note especially the allocations.

ensure specialization on the skip function

---

README.md
src/NearestNeighbors.jl
src/ball_tree.jl
src/brute_tree.jl
src/inrange.jl
src/kd_tree.jl
src/tree_ops.jl
test/test_inrange.jl

Added an efficient method for counting neighbors without storing their indexes.
**EDIT: This is out of date, see post below**
This was primarily achieved by reusing the index-accumulating vector for `inrange_points!`
```
@btime [(inrangecount(ctrees[j], (@view c.coordinates[:, c.abovethreshold]), r) .- k) ./ r ^ 2 for r ∈ radiussteps]
72.972 ms (701 allocations: 1.76 MiB)
@btime [(length.(inrange(ctrees[j], (@view c.coordinates[:, c.abovethreshold]), r)) .- k) ./ r ^ 2 for r ∈ radiussteps]
190.149 ms (30129 allocations: 163.86 MiB)
```
The above calculates a density gradient around each point, with 100 test points and 25 radius steps against a tree of ~20,000.
This PR cuts execution time of the above code by 2.6x, allocations by 28.7x, and allocation amount by 93.1x.
An important feature …

Add `inrangecount` for efficient counting of neighbors

---

.gitignore
src/hyperspheres.jl

This PR adds a constructor to `HyperSphere` that accepts an `AbstractVector`.
This constructor is needed because of this function:
```julia
function _inrange(tree::BallTree{V},
point::AbstractVector,
radius::Number,
idx_in_ball::Union{Nothing, Vector{Int}}) where {V}
ball = HyperSphere(convert(V, point), convert(eltype(V), radius))  # The "query ball"
return inrange_kernel!(tree, 1, point, ball, idx_in_ball)  # Call the recursive range finder
end
```
The type parameter `V` of `BallTree` accepts any subtype of `AbstractVector`, but in the current code, `HyperSphere` does not have a constructor that accepts `AbstractVector`s.

Add generic constructor to `HyperSphere`

---

src/NearestNeighbors.jl
src/inrange.jl
src/knn.jl

For some reason we did the conversion to static vectors "wholesale" for the whole input matrix instead of just doing it point by point.
```julia 
julia> using NearestNeighbors
julia> tree = KDTree(rand(3, 100));
julia> @time input = rand(3, 10^6);
0.036092 seconds (2 allocations: 22.888 MiB, 89.04% gc time)
julia> @time knn(tree, input, 5);
0.368772 seconds (2.00 M allocations: 221.253 MiB, 5.09% gc time)
julia> @time knn(tree, input, 5);
0.395747 seconds (2.00 M allocations: 198.365 MiB, 17.31% gc time)
```
We can see we save copying that 20 mb input.

avoid copying inputs when doing a `knn` or `inrange` for a matrix input

---

src/NearestNeighbors.jl
src/evaluation.jl
src/kd_tree.jl
test/test_knn.jl

Fixes https://github.com/KristofferC/NearestNeighbors.jl/issues/169. cc @aplavin
Looking at this code now (for the first time in many years) I am not really happy with how it looks. Ideally we should only use the functions provided by Distances.jl and not need any `eval_pow` and `eval_diff` stuff.

some fixes for weighted metrics

---

Project.toml
src/kd_tree.jl
test/test_knn.jl

In #166 the `HyperRectangle` struct was changed to use the same vector type as the input data for the mins and maxes, and to use `StaticArrays.setindex` for "mutation". Since this function is not implemented for all working input types (for example `Tensors.Vec`) there was an `MethodError` thrown. This patch adds `NearestNeighbors.setindex` which dispatches to `StaticArrays.setindex` for `<: StaticArray.StaticArray` and for other types casts to `SVector` and then back to the original type after mutating.

Fix tree construction for vectors without `StaticArrays.setindex`

---

src/ball_tree.jl
src/hyperspheres.jl

We can:
- Avoid computing the distance in `encloses` an extra time when searching since we already computed it in `intersect` earlier.
- Avoid computing the distance in encloses if the second hyper sphere has a larger radius then the other (which means the first one cannot enclose the second one).
- Avoid computing the "end reduction" (like `sqrt`) for some metrics when checking intersections and enclosures by "squaring both sides".
Some kind of benchmark:
```
julia> x = BallTree(rand(3,10^5));
julia> @time inrange(x, rand(3,10^5), 0.01);
0.186999 seconds (133.77 k allocations: 11.731 MiB)
julia> @time inrange(x, rand(3,10^5), 0.01);
0.155827 seconds (133.87 k allocations: 11.739 MiB)
```

optimize some hypersphere checks for minkowski metrics

---

src/ball_tree.jl
src/kd_tree.jl
src/tree_ops.jl

```
using Revise, StableRNGs
using NearestNeighbors
data = rand(StableRNG(1), 3, 10^4);
x = BallTree(data);
v = rand(StableRNG(1), 3);
using GFlops
@count_ops inrange(x, v, 0.01)
```
Master:
```
Flop Counter: 1491 flop
┌──────┬─────────┐
│      │ Float64 │
├──────┼─────────┤
│  add │     438 │
│  sub │     468 │
│  mul │     555 │
│ sqrt │      30 │
└──────┴─────────┘
```
PR:
```
Flop Counter: 1491 flop
┌─────┬─────────┐
│     │ Float64 │
├─────┼─────────┤
│ add │     438 │
│ sub │     468 │
│ mul │     558 │
└─────┴─────────┘
```
No more square roots 🎉.

avoid some square rooting to check distances

---

README.md
src/ball_tree.jl
src/kd_tree.jl

Since this package was written CPUs have in general become faster (at a rate faster than memory can be fetched). The choice of a good default leafsize might therefore be worth reevaluating. Remember that with a large leafsize we have to traverse fewer nodes in the tree while we have to explicitly check more points for the distance. As CPUs gets faster compared to memory it is generally expected that `leafsize` can be increased.
The checks / benchmarks below are artificial but in lack of real benchmark data it is the best I have.
First, let's look at the number of flops required for a leafsize of 10 vs 25 (here using a BallTree):
```julia-repl
julia> using StaticArrays, NearestNeighbors, StableRNGs
julia> using NearestNeighbors: HyperSphere
julia> V = SVector{3, Float64}
julia> data = …
```

bump the default leafsize from 10 to 25

---

src/evaluation.jl
src/hyperrectangles.jl
src/kd_tree.jl
test/runtests.jl

It is unclear to me if this "optimization" can be done with Chebyshev but at least it gives the wrong values now (see the added test I made by just asserting that the optimized min computation gave the same result as the one from scratch) so disable it for now.
Have to benchmark that pulling this computation out into its own function didn't make things worse.

Disable fast path update for minimum distance to hyper rectangle for `Chebyshev` since it doesn't work
