src/NearestNeighbors.jl
src/ball_tree.jl
src/debugging.jl
src/evaluation.jl
src/hyperrectangles.jl
src/hyperspheres.jl
src/kd_tree.jl
src/knn.jl
src/tree_data.jl
src/tree_ops.jl
src/utilities.jl
test/test_inrange.jl
test/test_knn.jl

More comments, turn on precompilation + other stuff.

General stuff

---

README.md

balltree = BallTree(data)
idxs = (kdtree, point, r, true)   #kdtree -> balltree
Nice package!

Fixed a small mistake in the final example.

---

.travis.yml

(no need to re-tag for travis-only changes)

Use the default travis script, add testing against 0.5 rc's

---

.gitignore
benchmarks/generate_report.jl
benchmarks/runbenchmarks.jl

In order to test that #29 does not introduce regressions

add benchmarks

---

src/ball_tree.jl
src/hyperrectangles.jl
src/knn.jl
test/test_inrange.jl
test/test_knn.jl

Enable construction and queries for empty trees

---

src/NearestNeighbors.jl

I want to be able to define a member of type `NNTree` in my struct here - https://github.com/Shushman/LocalApproximationValueIteration.jl/blob/master/src/localNNValueFunctionApproximator.jl#L6
Is this the right way to do this? I am fairly new to Julia so bear with me!

Exporting NNTree in NearestNeighbors Module

---

.travis.yml
Project.toml
REQUIRE
appveyor.yml
src/datafreetree.jl
src/inrange.jl
src/knn.jl
test/test_datafreetree.jl

Depwarns and CI for julia 1.0

---

src/utilities.jl

fix inbounds to be on correct block

---

src/inrange.jl
src/knn.jl
test/test_inrange.jl
test/test_knn.jl

A simple change to make the function work with matrix views as well.

Accept any AbstractMatrix in knn (e.g. views)

---

README.md

Add a little more explanation as suggested in https://github.com/KristofferC/NearestNeighbors.jl/issues/85

Add to docs: more hand-holding for which vector-of-vector types of data are valid

---

benchmarks/Project.toml
benchmarks/generate_report.jl
benchmarks/runbenchmarks.jl

These seems like useful benchmarking code for this package.

Get code running in Julia 1.3

---

src/NearestNeighbors.jl

I think this is the most commonly used functions so makes sense to try to cache this.

add some code to run during precompilation

---

src/NearestNeighbors.jl
src/brute_tree.jl

Adresses https://github.com/KristofferC/NearestNeighbors.jl/issues/99

Allow usage of semi and pre-metrics with BruteTree

---

src/hyperrectangles.jl
src/kd_tree.jl
test/test_knn.jl

Looks like avoiding an extra type parameter did not work out.
Fixes #173

use a separate parameter for the hyper rectangle

---

src/kd_tree.jl

Previously, the `split_dim` had to be aligned giving:
```julia-repl
julia> sizeof(NearestNeighbors.KDNode{Float64})
16
```
This instead SoAs that struct so that the values and dimensions are stored separately and can thus be stored without paying the alignment cost:
```julia-repl
julia> r = rand(3, 10^6) ;
julia> tree = KDTree(r);
julia> sizeof(tree.nodes)
1599984
julia> sizeof(tree.split_dims) + sizeof(tree.split_vals)
899991
```
I see roughly a 5% improvement in `knn` from this.

KDTree: SoA the `Node` struct to avoid paying alignment cost to store the split dimension

---

README.md

read through it manually as well obviously, looks better to me
Some manual fix ups as well

chatgpt the README

---

src/inrange.jl
src/knn.jl
test/test_inrange.jl
test/test_knn.jl

Fixes https://github.com/KristofferC/NearestNeighbors.jl/issues/176

allow views as input to query functions

---

README.md
src/ball_tree.jl
src/hyperrectangles.jl
src/hyperspheres.jl
src/kd_tree.jl
src/tree_data.jl
src/tree_ops.jl
src/utilities.jl
test/test_monkey.jl

Just going through the code and improve it when I see it. Have done some spot benchmarks but should do it properly as well.
Many of the improvements are left over from when we didn't use many static vectors and therefore unrolled many things manually. With static vectors these can be written in vectorized form without loss of performance.

Grab bag of fixups / improvements

---

README.md
src/NearestNeighbors.jl
src/ball_tree.jl
src/brute_tree.jl
src/inrange.jl
src/kd_tree.jl
src/knn.jl
src/tree_ops.jl
src/utilities.jl
test/test_inrange.jl
test/test_knn.jl

This does not add the "vectorized" versions of these (when searching for multiple points in one call) because I am unsure about the future of those.
Closes https://github.com/KristofferC/NearestNeighbors.jl/issues/160, https://github.com/KristofferC/NearestNeighbors.jl/issues/81
Closes https://github.com/KristofferC/NearestNeighbors.jl/issues/147

Add mutating version of `knn` and `inrange`

---

README.md

Closes https://github.com/KristofferC/NearestNeighbors.jl/issues/152

improve docs w.r.t what metrics can be used

---

src/ball_tree.jl
src/brute_tree.jl
test/runtests.jl

Fixes https://github.com/KristofferC/NearestNeighbors.jl/issues/74

relax some types to make things work with views

---

README.md

Closes https://github.com/KristofferC/NearestNeighbors.jl/issues/156

add a blurb about package not being suitable for very high dimensional points

---

src/hyperrectangles.jl
src/kd_tree.jl
test/runtests.jl
test/test_knn.jl

fix min max hyperrec

---

src/hyperrectangles.jl
test/test_knn.jl

revert "vectorize the compute_bbox function"

---

src/utilities.jl
test/test_inrange.jl
test/test_knn.jl

Fixes https://github.com/KristofferC/NearestNeighbors.jl/issues/207

fix inferrability of return value with KDTree created from matrix of points
